### ISSUE TITLE
plus4 zip codes not ignored

### ISSUE THREAD

**Issue by wolfeclw** [cole-brokamp/cchmc_batch_geocoder#8]
Running address (Cincinnati Zoo) with and without plus4 zip code yields different results--maybe non-alphanumeric characters (i.e. hyphen) is removed but extra digits are not?

[geocoder_zip_issue_geocoded.csv.zip](https://github.com/cole-brokamp/cchmc_batch_geocoder/files/3650362/geocoder_zip_issue_geocoded.csv.zip)

**Comment by cole-brokamp** [comment]
This is a known issue, thanks for bringing it up. A fix might be tough because the program doesn't have access to the zip code alone, only the entire address string.  There might be a way to extract the address components from the `usaddress` library and then ensure only the first five digits of zip codes are used, but for now, we have to do a better job reminding users that zip codes with more than 5 digits can be highly problematic.

**Comment by cole-brokamp** [comment]
looking back at the address formatting tips for DeGAUSS, it seems like plus4 zip codes could work _only_ if the hyphen is included.  No hyphen will lead to problems.

https://github.com/cole-brokamp/DeGAUSS/wiki/Geocoding-with-DeGAUSS#address-string-formatting

**Comment by cole-brokamp** [comment]
I updated the README to include our address formatting tips (1069800d6bc3208ad77bda5fd97e27807a69f17d).  Closing for now unless we can think of a better way to deal with this issue.

**Comment by cole-brokamp** [comment]
when the R code strips all non-alphanumeric characters, it also removes the dash in a 5+4 zipcode, meaning that if the zip codes originally includes a dash, it will cause a problem in the geocoder because of this (when it didn't before)

**Comment by cole-brokamp** [comment]
should we leave dashes in?

https://github.com/cole-brokamp/cchmc_batch_geocoder/blob/1069800d6bc3208ad77bda5fd97e27807a69f17d/geocode.R#L26-L30
